server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: operation-service
          uri: lb://operation-service
          predicates:
            - Path=/operations/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/profile/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/request/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**